version: 0.2
env:
  parameter-store:
    GIT_USER_EMAIL: "github-user-email"
    NPM_AUTH_TOKEN: "/aws/reference/secretsmanager/npm-access-token"
    GITHUB_ACCESS_TOKEN: "/aws/reference/secretsmanager/github-access-token"
    NPM_REGISTRY_LOGIN_URL: "npm-repository-auth-url"

phases:
  install:
    commands:
      - echo $GIT_USER_EMAIL
      - echo $NPM_AUTH_TOKEN
      - echo $GITHUB_OAUTH_TOKEN
      - echo $NPM_REGISTRY_LOGIN_URL
      - aws cloudformation deploy --stack-name rtm-kit-docs --template-file ./aws/docs-cft.yml --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --parameter-overrides =$SPA_BUCKET_NAME || ( aws cloudformation describe-stack-events --stack-name $STACK_NAME && exit 1)
