version: 0.2
phases:
  install:
    commands:
      - echo "$NPM_REGISTRY_LOGIN_URL:_authToken=$NPM_AUTH_TOKEN" >> $HOME/.npmrc
      - npm install -g lerna
  pre_build:
    commands:
    - npm run prepare
  build:
    commands:
      - cat $HOME/.npmrc
      - npm whoami
      - npm run test
      - npm run release
