version: 0.2
phases:
  install:
    commands:
      - npm install -g npm
      - npm install -g lerna
      - git checkout master
      - echo "$NPM_REGISTRY_LOGIN_URL:_authToken=$NPM_AUTH_TOKEN" >> $HOME/.npmrc
      - echo "registry=https:$NPM_REGISTRY_LOGIN_URL" >> $HOME/.npmrc
      - echo "always-auth=true" >> $HOME/.npmrc
      - git remote set-url origin $GITHUB_URL
      - git config --global user.email $GIT_USER_EMAIL
      - git config --global user.name $GIT_USERNAME
      - npm set unsafe-perm false
  pre_build:
    commands:
      - cat $HOME/.npmrc
      - lerna bootstrap --no-ci --hoist
  build:
    commands:
      - npm run test
      - npm run release  --loglevel silly
