version: 0.2
env:
  parameter-store:
    AWS_ACCESS_KEY_ID: "component-website-access-key"
    AWS_SECRET_ACCESS_KEY: "component-website-secret-key"
    GIT_USER_EMAIL: "github-user-email"
    GIT_USER_NAME: "github-user-name"
    NPM_AUTH_TOKEN: "/aws/reference/secretsmanager/npm-access-token"
    NPM_REGISTRY_LOGIN_URL: "npm-repository-auth-url"

phases:
  install:
    commands:
      # Need to manually checkout master here so that the lerna step later does not complain about a detached head
      - git checkout master
      - npm install -g npm
      - npm install -g lerna
      - npm set registry http://registry.npmjs.org/
      - npm set always-auth true
      - npm set unsafe-perm true
      - echo "$NPM_REGISTRY_LOGIN_URL:_authToken=$NPM_AUTH_TOKEN" >> $HOME/.npmrc
      - echo "@rtm:registry=https:$NPM_REGISTRY_LOGIN_URL" >> $HOME/.npmrc
      - git remote set-url origin $GITHUB_URL
      - git config --global user.email $GIT_USER_EMAIL
      - git config --global user.name $GIT_USER_NAME
  pre_build:
    commands:
      - lerna bootstrap --no-ci
  build:
    commands:
      - npm run build:ci --parallel
      - npm run copy:builds # this copies the build files and places in the dist/ folder for the component CDN
  post_build:
    commands:
      - npm run test:ci
      - git status
      - npm run release
      - if [ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ] ; then exit 1; fi
      - aws s3 cp ./dist/ s3://$CDN_BUCKET_NAME/rtm-ui/libs --acl public-read --exclude "*" --include "*.min.js" --recursive
cache:
  paths:
    - "./node_modules/**/*"
