version: 0.2
phases:
  install:
    commands:
      - aws ecr batch-get-image --registry-id=676559443024 --repository-name custom-codebuild-image-develop --image-ids=imageTag=latest
      - npm ci
      - npm config list

  pre_build:
    commands:
      - npm run bootstrap
      - npm run build:ci

  build:
    commands:
      - npm run test:ci
      - npm run copy:builds
      - npm run build:docs
# artifacts:
#   secondary-artifacts:
#     api:
#       base-directory: .docz/dist
#       files:
#         - "**/*"
#     ui:
#       base-directory: .docz/dist
#       files:
#         - "**/*"
