version: 0.2
phases:
  install:
    commands:
      - npm install -g npm
      - npm install -g lerna
      - git checkout master
  pre_build:
    commands:
    - lerna bootstrap --no-ci --hoist
  build:
    commands:
      - npm run test
      - echo "$NPM_REGISTRY_LOGIN_URL:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
      - echo "registry=https:$NPM_REGISTRY_LOGIN_URL" >> .npmrc
      - echo "always-auth=true" >> .npmrc
      - npm set unsafe-perm false
      - npm run release
